#!/bin/bash

source /setup/user.sh
sleep 1

source /setup/protocol.sh
sleep 1

echo 'lektor ALL=(ALL) NOPASSWD: ALL' > /etc/sudoers.d/00_lektor


function install_aurs() {
    sudo -H -u lektor bash -c 'git clone https://aur.archlinux.org/yay /tmp/yay' > /dev/null
    sudo -H -u lektor bash -c 'makepkg -sric --dir /tmp/yay --noconfirm' > /dev/null
}


function install_hypr() {
    pacman -S uwsm hyprland hyprpolkitagent hypridle hyprlock xdg-desktop-portal-hyprland pipewire pipewire-pulse pipewire-jack wireplumber pavucontrol kitty qt5-wayland qt6-wayland ttf-jetbrains-mono-nerd ttf-droid btop nautilus nautilus-image-converter seahorse-nautilus sushi mako waybar wofi evolution gnome-calendar wl-clipboard cliphist mailcap --noconfirm
    sudo -H -u lektor bash -c 'yay -S hyprshot --noconfirm && yay -Yc' 

    systemctl --global enable hyprpolkitagent
    systemctl --global enable hypridle.service
    systemctl --global enable waybar
}


function install_sddm() {
    sudo pacman -S sddm --noconfirm
    sudo git clone https://github.com/linux-blackbird/login  /usr/share/sddm/themes/login
    sudo systemctl enable sddm
}


function install_icon() {
    sudo pacman -S papirus-icon-theme --noconfirm
    sudo git clone https://github.com/linux-blackbird/themes /usr/share/themes/blackbird
}


function install_pkgs() {
    pacman -S flatpak gnome-software --noconfirm
    sudo -H -u lektor bash -c 'flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo' 
    sudo -H -u $MAKEUSER bash -c 'flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo'
    sudo flatpak override --env=GTK_THEME=blackbird
    sudo flatpak override --env=ICON_THEME=Papirus-Dark
}


function install_devs() {
    sudo chown root:root /opt/visual-studio-code/chrome-sandbox
    sudo chmod 4775 /opt/visual-studio-code/chrome-sandbox
}


function install_brws() {
    flatpak install --system --noninteractive org.mozilla.firefox 
    sudo -H -u lektor bash -c "yay -S google-chrome --noconfirm" yay -S
}


function install_play() {
    pacman -S mpd mpc xfmpc --noconfirm
}


function install_note() {
    pacman -S hugo obsidian --noconfirm
}


install_aurs &&
install_hypr &&
install_sddm &&
install_icon &&
install_pkgs &&
install_devs &&
install_brws &&
install_play &&
install_note &&


echo 'lektor ALL=(ALL:ALL) ALL' > /etc/sudoers.d/00_lektor